before:
  hooks:
    - go mod download

builds:
- binary: "{{.ProjectName}}_v{{.Version}}"
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
  - amd64
archive:
  format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
release:
  github:
    owner: Brightspace
    name: terraform-provider-evident
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
# Disable until switch from auto to manual IAM credentials (secrets has no API atm)
# s3:
# -
#   bucket: tfreg
#   region: us-east-1
#   folder: "ace/providers/{{.ProjectName}}/{{.Version}}"