before:
  hooks:
  - go get -v -t -d
builds:
- main: main.go
  binary: terraform-provider-evident_v{{.Version}}
  goos:
    - linux
    - windows
  goarch:
  - amd64
archive:
  format: zip
s3:
-
  bucket: d2l-terraform-registry
  region: us-east-1
  folder: "providers/terraform-provider-evident/{{.Version}}"